[package]
name = "csci-common"
version = "0.1.0"
authors = ["Atmelfan <gustavp@gpa-robotics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nng = "1.0"